version: '2.4'
services:
  xenial:
    build: ../../dockerfiles/xenial
    # See https://github.com/pypa/setuptools/issues/2355 for why SETUPTOOLS_USE_DISTUTILS must be set
    command: bash -c "cd src && tox -exenial && SETUPTOOLS_USE_DISTUTILS=stdlib dpkg-buildpackage -d -uc -us && mv ../*.deb ../dist/"
    volumes:
     - ../..:/work
