version: '2.4'
services:
  xenial:
    build: ../../dockerfiles/xenial
    command: bash -c "cd src && tox -exenial && dpkg-buildpackage -d -uc -us && mv ../*.deb ../dist/"
    volumes:
     - ../..:/work
