itest:
  build: ../../dockerfiles/itest/itest_xenial
  hostname: itesthost.itestdomain
  volumes:
   - ../..:/work
  environment:
    CONTAINER_PREFIX: xenial
  links:
   - xenialservicetwo
   - xenialservicethree
   - xenialservicethreechaos
   - xenialserviceone
   - xenialzookeeper

xenialservicethree:
  build: ../../dockerfiles/itest/service_three

xenialserviceone:
  build: ../../dockerfiles/itest/service_one

xenialzookeeper:
  build: ../../dockerfiles/itest/zookeeper

xenialservicethreechaos:
  build: ../../dockerfiles/itest/service_three

xenialservicetwo:
  build: ../../dockerfiles/itest/service_two
