version: '2.4'
services:
  itest:
    build: ../../dockerfiles/itest/itest_trusty
    hostname: itesthost.itestdomain
    volumes:
     - ../..:/work
    environment:
      CONTAINER_PREFIX: trusty
    links:
     - trustyservicetwo
     - trustyservicethree
     - trustyservicethreechaos
     - trustyserviceone
     - trustyzookeeper
     - trustyservicethree_endpoint_timeout

  trustyservicethree_endpoint_timeout:
    build: ../../dockerfiles/itest/service_three

  trustyservicethree:
    build: ../../dockerfiles/itest/service_three

  trustyserviceone:
    build: ../../dockerfiles/itest/service_one

  trustyzookeeper:
    build: ../../dockerfiles/itest/zookeeper

  trustyservicethreechaos:
    build: ../../dockerfiles/itest/service_three

  trustyservicetwo:
    build: ../../dockerfiles/itest/service_two
